export enum ENVEnum {
  DATABASE_URL = 'DATABASE_URL',
  PORT = 'PORT',
  NODE_ENV = 'NODE_ENV',
  JWT_SECRET = 'JWT_SECRET',
  JWT_EXPIRES_IN = 'JWT_EXPIRES_IN',
  MAIL_USER = 'MAIL_USER',
  MAIL_APP_PASSWORD = 'MAIL_APP_PASSWORD',
  OAUTH_CLIENT_ID = 'OAUTH_CLIENT_ID',
  OAUTH_CLIENT_SECRET = 'OAUTH_CLIENT_SECRET',
  FRONTEND_EMAIL_VERIFY_URL = 'FRONTEND_EMAIL_VERIFY_URL',
  FRONTEND_PASSWORD_RESET_URL = 'FRONTEND_PASSWORD_RESET_URL',
}
